apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-2
  annotations:
    security.knative.dev/authorizableOn: self
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-2
  template:
    metadata:
      labels:
        app: curl-2
    spec:
      containers:
      - name: curl
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
