apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args: ["-text=\"hello world\""]
        ports:
        - containerPort: 5678
          # name: http
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  annotations:
    security.knative.dev/authorizableOn: |
      {"apiVersion":"apps/v1","kind":"Deployment","namespace":"istio-example","selector":{"matchLabels":{"app":"echo"}}}
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      name: http