/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	securityv1alpha2 "github.com/yolocs/knative-policy-binding/pkg/apis/security/v1alpha2"
	versioned "github.com/yolocs/knative-policy-binding/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yolocs/knative-policy-binding/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/yolocs/knative-policy-binding/pkg/client/listers/security/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PolicyPodspecableBindingInformer provides access to a shared informer and lister for
// PolicyPodspecableBindings.
type PolicyPodspecableBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.PolicyPodspecableBindingLister
}

type policyPodspecableBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPolicyPodspecableBindingInformer constructs a new informer for PolicyPodspecableBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPolicyPodspecableBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPolicyPodspecableBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPolicyPodspecableBindingInformer constructs a new informer for PolicyPodspecableBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPolicyPodspecableBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha2().PolicyPodspecableBindings(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha2().PolicyPodspecableBindings(namespace).Watch(options)
			},
		},
		&securityv1alpha2.PolicyPodspecableBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *policyPodspecableBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPolicyPodspecableBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *policyPodspecableBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securityv1alpha2.PolicyPodspecableBinding{}, f.defaultInformer)
}

func (f *policyPodspecableBindingInformer) Lister() v1alpha2.PolicyPodspecableBindingLister {
	return v1alpha2.NewPolicyPodspecableBindingLister(f.Informer().GetIndexer())
}
