/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	securityv1alpha1 "github.com/yolocs/knative-policy-binding/pkg/apis/security/v1alpha1"
	versioned "github.com/yolocs/knative-policy-binding/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yolocs/knative-policy-binding/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/yolocs/knative-policy-binding/pkg/client/listers/security/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AuthorizableBindingInformer provides access to a shared informer and lister for
// AuthorizableBindings.
type AuthorizableBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AuthorizableBindingLister
}

type authorizableBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAuthorizableBindingInformer constructs a new informer for AuthorizableBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAuthorizableBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAuthorizableBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAuthorizableBindingInformer constructs a new informer for AuthorizableBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAuthorizableBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha1().AuthorizableBindings(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha1().AuthorizableBindings(namespace).Watch(options)
			},
		},
		&securityv1alpha1.AuthorizableBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *authorizableBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAuthorizableBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *authorizableBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securityv1alpha1.AuthorizableBinding{}, f.defaultInformer)
}

func (f *authorizableBindingInformer) Lister() v1alpha1.AuthorizableBindingLister {
	return v1alpha1.NewAuthorizableBindingLister(f.Informer().GetIndexer())
}
