/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	securityv1alpha1 "github.com/yolocs/knative-policy-binding/pkg/apis/security/v1alpha1"
	versioned "github.com/yolocs/knative-policy-binding/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yolocs/knative-policy-binding/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/yolocs/knative-policy-binding/pkg/client/listers/security/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// OpenPolicyInformer provides access to a shared informer and lister for
// OpenPolicies.
type OpenPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.OpenPolicyLister
}

type openPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewOpenPolicyInformer constructs a new informer for OpenPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOpenPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOpenPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredOpenPolicyInformer constructs a new informer for OpenPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOpenPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha1().OpenPolicies(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha1().OpenPolicies(namespace).Watch(options)
			},
		},
		&securityv1alpha1.OpenPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *openPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOpenPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *openPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securityv1alpha1.OpenPolicy{}, f.defaultInformer)
}

func (f *openPolicyInformer) Lister() v1alpha1.OpenPolicyLister {
	return v1alpha1.NewOpenPolicyLister(f.Informer().GetIndexer())
}
