/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// HTTPPolicyListerExpansion allows custom methods to be added to
// HTTPPolicyLister.
type HTTPPolicyListerExpansion interface{}

// HTTPPolicyNamespaceListerExpansion allows custom methods to be added to
// HTTPPolicyNamespaceLister.
type HTTPPolicyNamespaceListerExpansion interface{}

// HTTPPolicyBindingListerExpansion allows custom methods to be added to
// HTTPPolicyBindingLister.
type HTTPPolicyBindingListerExpansion interface{}

// HTTPPolicyBindingNamespaceListerExpansion allows custom methods to be added to
// HTTPPolicyBindingNamespaceLister.
type HTTPPolicyBindingNamespaceListerExpansion interface{}

// PolicyPodspecableBindingListerExpansion allows custom methods to be added to
// PolicyPodspecableBindingLister.
type PolicyPodspecableBindingListerExpansion interface{}

// PolicyPodspecableBindingNamespaceListerExpansion allows custom methods to be added to
// PolicyPodspecableBindingNamespaceLister.
type PolicyPodspecableBindingNamespaceListerExpansion interface{}
