/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AuthorizableBindingListerExpansion allows custom methods to be added to
// AuthorizableBindingLister.
type AuthorizableBindingListerExpansion interface{}

// AuthorizableBindingNamespaceListerExpansion allows custom methods to be added to
// AuthorizableBindingNamespaceLister.
type AuthorizableBindingNamespaceListerExpansion interface{}

// EventPolicyListerExpansion allows custom methods to be added to
// EventPolicyLister.
type EventPolicyListerExpansion interface{}

// EventPolicyNamespaceListerExpansion allows custom methods to be added to
// EventPolicyNamespaceLister.
type EventPolicyNamespaceListerExpansion interface{}

// OpenPolicyListerExpansion allows custom methods to be added to
// OpenPolicyLister.
type OpenPolicyListerExpansion interface{}

// OpenPolicyNamespaceListerExpansion allows custom methods to be added to
// OpenPolicyNamespaceLister.
type OpenPolicyNamespaceListerExpansion interface{}

// PolicyBindingListerExpansion allows custom methods to be added to
// PolicyBindingLister.
type PolicyBindingListerExpansion interface{}

// PolicyBindingNamespaceListerExpansion allows custom methods to be added to
// PolicyBindingNamespaceLister.
type PolicyBindingNamespaceListerExpansion interface{}
