/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/yolocs/knative-policy-binding/pkg/apis/security/v1alpha1"
	scheme "github.com/yolocs/knative-policy-binding/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AuthorizableBindingsGetter has a method to return a AuthorizableBindingInterface.
// A group's client should implement this interface.
type AuthorizableBindingsGetter interface {
	AuthorizableBindings(namespace string) AuthorizableBindingInterface
}

// AuthorizableBindingInterface has methods to work with AuthorizableBinding resources.
type AuthorizableBindingInterface interface {
	Create(*v1alpha1.AuthorizableBinding) (*v1alpha1.AuthorizableBinding, error)
	Update(*v1alpha1.AuthorizableBinding) (*v1alpha1.AuthorizableBinding, error)
	UpdateStatus(*v1alpha1.AuthorizableBinding) (*v1alpha1.AuthorizableBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AuthorizableBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.AuthorizableBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AuthorizableBinding, err error)
	AuthorizableBindingExpansion
}

// authorizableBindings implements AuthorizableBindingInterface
type authorizableBindings struct {
	client rest.Interface
	ns     string
}

// newAuthorizableBindings returns a AuthorizableBindings
func newAuthorizableBindings(c *SecurityV1alpha1Client, namespace string) *authorizableBindings {
	return &authorizableBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the authorizableBinding, and returns the corresponding authorizableBinding object, and an error if there is any.
func (c *authorizableBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.AuthorizableBinding, err error) {
	result = &v1alpha1.AuthorizableBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("authorizablebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AuthorizableBindings that match those selectors.
func (c *authorizableBindings) List(opts v1.ListOptions) (result *v1alpha1.AuthorizableBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AuthorizableBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("authorizablebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested authorizableBindings.
func (c *authorizableBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("authorizablebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a authorizableBinding and creates it.  Returns the server's representation of the authorizableBinding, and an error, if there is any.
func (c *authorizableBindings) Create(authorizableBinding *v1alpha1.AuthorizableBinding) (result *v1alpha1.AuthorizableBinding, err error) {
	result = &v1alpha1.AuthorizableBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("authorizablebindings").
		Body(authorizableBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a authorizableBinding and updates it. Returns the server's representation of the authorizableBinding, and an error, if there is any.
func (c *authorizableBindings) Update(authorizableBinding *v1alpha1.AuthorizableBinding) (result *v1alpha1.AuthorizableBinding, err error) {
	result = &v1alpha1.AuthorizableBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("authorizablebindings").
		Name(authorizableBinding.Name).
		Body(authorizableBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *authorizableBindings) UpdateStatus(authorizableBinding *v1alpha1.AuthorizableBinding) (result *v1alpha1.AuthorizableBinding, err error) {
	result = &v1alpha1.AuthorizableBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("authorizablebindings").
		Name(authorizableBinding.Name).
		SubResource("status").
		Body(authorizableBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the authorizableBinding and deletes it. Returns an error if one occurs.
func (c *authorizableBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("authorizablebindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *authorizableBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("authorizablebindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched authorizableBinding.
func (c *authorizableBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AuthorizableBinding, err error) {
	result = &v1alpha1.AuthorizableBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("authorizablebindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
