/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/yolocs/knative-policy-binding/pkg/apis/security/v1alpha1"
	scheme "github.com/yolocs/knative-policy-binding/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OpenPoliciesGetter has a method to return a OpenPolicyInterface.
// A group's client should implement this interface.
type OpenPoliciesGetter interface {
	OpenPolicies(namespace string) OpenPolicyInterface
}

// OpenPolicyInterface has methods to work with OpenPolicy resources.
type OpenPolicyInterface interface {
	Create(*v1alpha1.OpenPolicy) (*v1alpha1.OpenPolicy, error)
	Update(*v1alpha1.OpenPolicy) (*v1alpha1.OpenPolicy, error)
	UpdateStatus(*v1alpha1.OpenPolicy) (*v1alpha1.OpenPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.OpenPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.OpenPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OpenPolicy, err error)
	OpenPolicyExpansion
}

// openPolicies implements OpenPolicyInterface
type openPolicies struct {
	client rest.Interface
	ns     string
}

// newOpenPolicies returns a OpenPolicies
func newOpenPolicies(c *SecurityV1alpha1Client, namespace string) *openPolicies {
	return &openPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the openPolicy, and returns the corresponding openPolicy object, and an error if there is any.
func (c *openPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.OpenPolicy, err error) {
	result = &v1alpha1.OpenPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("openpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OpenPolicies that match those selectors.
func (c *openPolicies) List(opts v1.ListOptions) (result *v1alpha1.OpenPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OpenPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("openpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested openPolicies.
func (c *openPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("openpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a openPolicy and creates it.  Returns the server's representation of the openPolicy, and an error, if there is any.
func (c *openPolicies) Create(openPolicy *v1alpha1.OpenPolicy) (result *v1alpha1.OpenPolicy, err error) {
	result = &v1alpha1.OpenPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("openpolicies").
		Body(openPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a openPolicy and updates it. Returns the server's representation of the openPolicy, and an error, if there is any.
func (c *openPolicies) Update(openPolicy *v1alpha1.OpenPolicy) (result *v1alpha1.OpenPolicy, err error) {
	result = &v1alpha1.OpenPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("openpolicies").
		Name(openPolicy.Name).
		Body(openPolicy).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *openPolicies) UpdateStatus(openPolicy *v1alpha1.OpenPolicy) (result *v1alpha1.OpenPolicy, err error) {
	result = &v1alpha1.OpenPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("openpolicies").
		Name(openPolicy.Name).
		SubResource("status").
		Body(openPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the openPolicy and deletes it. Returns an error if one occurs.
func (c *openPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("openpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *openPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("openpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched openPolicy.
func (c *openPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OpenPolicy, err error) {
	result = &v1alpha1.OpenPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("openpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
