/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/yolocs/knative-policy-binding/pkg/apis/security/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOpenPolicies implements OpenPolicyInterface
type FakeOpenPolicies struct {
	Fake *FakeSecurityV1alpha1
	ns   string
}

var openpoliciesResource = schema.GroupVersionResource{Group: "security.knative.dev", Version: "v1alpha1", Resource: "openpolicies"}

var openpoliciesKind = schema.GroupVersionKind{Group: "security.knative.dev", Version: "v1alpha1", Kind: "OpenPolicy"}

// Get takes name of the openPolicy, and returns the corresponding openPolicy object, and an error if there is any.
func (c *FakeOpenPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.OpenPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(openpoliciesResource, c.ns, name), &v1alpha1.OpenPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenPolicy), err
}

// List takes label and field selectors, and returns the list of OpenPolicies that match those selectors.
func (c *FakeOpenPolicies) List(opts v1.ListOptions) (result *v1alpha1.OpenPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(openpoliciesResource, openpoliciesKind, c.ns, opts), &v1alpha1.OpenPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OpenPolicyList{ListMeta: obj.(*v1alpha1.OpenPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.OpenPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested openPolicies.
func (c *FakeOpenPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(openpoliciesResource, c.ns, opts))

}

// Create takes the representation of a openPolicy and creates it.  Returns the server's representation of the openPolicy, and an error, if there is any.
func (c *FakeOpenPolicies) Create(openPolicy *v1alpha1.OpenPolicy) (result *v1alpha1.OpenPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(openpoliciesResource, c.ns, openPolicy), &v1alpha1.OpenPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenPolicy), err
}

// Update takes the representation of a openPolicy and updates it. Returns the server's representation of the openPolicy, and an error, if there is any.
func (c *FakeOpenPolicies) Update(openPolicy *v1alpha1.OpenPolicy) (result *v1alpha1.OpenPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(openpoliciesResource, c.ns, openPolicy), &v1alpha1.OpenPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOpenPolicies) UpdateStatus(openPolicy *v1alpha1.OpenPolicy) (*v1alpha1.OpenPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(openpoliciesResource, "status", c.ns, openPolicy), &v1alpha1.OpenPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenPolicy), err
}

// Delete takes name of the openPolicy and deletes it. Returns an error if one occurs.
func (c *FakeOpenPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(openpoliciesResource, c.ns, name), &v1alpha1.OpenPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOpenPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(openpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.OpenPolicyList{})
	return err
}

// Patch applies the patch and returns the patched openPolicy.
func (c *FakeOpenPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OpenPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(openpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.OpenPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenPolicy), err
}
